### ISSUE TITLE
CFBundleShortVersionString and CFBundleVersion are missing in macOS apps

### ISSUE THREAD

**Issue by cdwmhcc** [tamnguyenvan/screenvivid#1]
## General information:

* OS name:  macOS
* ScreenVivid version: 1.1.3

## Description of the issue

The `Info.plist` file of the ScreenVivid macOS application is missing the required keys for `CFBundleShortVersionString` and `CFBundleVersion`. These keys are essential for defining the public version of the application and the build version respectively, which are used by macOS during application installation and updates.

## Expected behavior

The Info.plist file should include the following keys and values to ensure the application's versioning is recognized correctly by macOS:
```
<key>CFBundleShortVersionString</key>
<string>1.1.3</string>
<key>CFBundleVersion</key>
<string>277</string>
```

## Actual Behavior
In the Info.plist file, the value of CFBundleShortVersionString is incorrect and the CFBundleVersion key is not defined. This omission can cause problems with deployment and version tracking.

**Comment by tamnguyenvan** [comment]
@cdwmhcc , Thanks for your detail report. I will take a look.
