### ISSUE TITLE
Installer problem

### ISSUE THREAD

**Issue by hubertsvk** [tamnguyenvan/screenvivid#3]
Hello,
I have download you latest installer for Windows, but before click to Finish, I have got error message
![image](https://github.com/user-attachments/assets/3b397414-c2f8-46bb-8e17-4617a84f92e6)

All files was deleted by Eset

**Comment by tamnguyenvan** [comment]
Please turn off your Eset and install it again. Due to budget constraints, I haven't yet been able to obtain a code signing certificate for the installer. So anti-virus software flags it as a trojan.
